Komis/Komis/Controllers/OpiniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Komis.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Komis.Controllers
{
    [Authorize]
    public class OpiniaController : Controller
    {
        private readonly IOpiniaRepository _opiniaRepository;

        public OpiniaController(IOpiniaRepository opiniaRepository)
        {
            _opiniaRepository = opiniaRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Opinia opinia)
        {
            if (ModelState.IsValid)
            {
            _opiniaRepository.DodajOpinie(opinia);

            return RedirectToAction("OpiniaWyslana");
            }

            return View(opinia);
        }

        public IActionResult OpiniaWyslana()
        {
            return View();
        }
    }
}

Komis/Komis/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/content/site.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/js/bootstrap.js" />

    <title>@ViewBag.Title</title>
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Opinia" asp-action="Index">Opinia</a>
                </li>
            </ul>

            @if (SignInManager.IsSignedIn(User))
            {
                <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="pull-right">
                    <ul class="nav navbar-nav ">
                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj!</a></li>
                    </ul>
                </form>
            }
            else
            {
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a id="loginLink" class="nav-link" asp-controller="Account" asp-action="Login">Logowanie</a>
                    </li>
                    <li class="nav-item">
                        <a id="registerLink" class="nav-link" asp-controller="Account" asp-action="Register">Rejestracja</a>
                    </li>
                </ul>
            }
        </div>

    </nav>

    <div class="container body-content"> 
        <div>
            @RenderBody()
        </div>
    </div>
   
</body>
</html>